# Default config for net_sentinel_v01

[general]
interval_seconds = 5
baseline_samples = 3
log_file = "net_sentinel_events.jsonl"

[thresholds]
# bytes/sec per-interface threshold to consider a spike suspicious
bytes_per_sec_threshold = 5_000_000  # 5 MB/s by default; tune to your network
new_outbound_connection = true
many_connections_threshold = 50 # number of simultaneous connections by one process
